# Applied Math 10: Computing for Science and Engineering

## SEC-01 : Numbers in computers

**Fall 2020**

---

### Learning objectives:

To be able to numerically answer questions involving logical variables and numerical operations, including addition, multiplication, division, roots, powers, exponentiation, logarithms, and trigonometric functions. To be able to generate arrays with desired properties, using functions from the `numpy` library. 

### Structure of the Section
Sections are designed as hands-on activities elucidating key concepts by examples and exercises, practicing problems similar to the homework, and reviewing difficult material. In the Section, we encourage you to collaborate with your peers and the teaching staff in achieving the learning goals.

### Learning Goals of this Section 

By the end of this Section, you will have achieved fluency on:
- The basics of python programming, with emphasis on numerical applications
- Importing and using the `numpy` module for basic numerical calculations
- Generating `numpy` arrays with specified properties


In [47]:
import numpy as np

<a id=format></a>

## Printing in Python

There are basically two ways of printing strings and variables in Python. 
- **With the percentage operator (%)**. In the example below, `%4.2f` is a format description for a float number indicating that the total number of digits are 4 with 2 decimal points. The `f` indicates a float and the format is 
```
%{width}.{precision}
```
- **With the format (f) string:** which is a more intuitive way of including variables in printing strings. With the f-strings we need not use the % operator.

In [9]:
# Example
name = "Bob"
age = 24.4567
hobby = 'painting'
print('Hello, I am %s, I am %2.0f years old, and I like %s.' % (name, age, hobby))

Hello, I am Bob, I am 24 years old, and I like painting.


In [12]:
# f-strings (format strings)
name = "Bob"
salary = 240000.45675
print(f'Hello, I am {name}, I earn ${salary:10.4f} a year, and I like {hobby}.')

Hello, I am Bob, I earn $240000.4568 a year, and I like painting.


In [13]:
# Reviewing decimal v. scientific notation

xx = np.pi
print('pi = %f' % xx)
print('pi = %5.3f' % xx)

print('pi = %2.3e' % xx)



pi = 3.141593
pi = 3.142
pi = 3.142e+00


In [23]:
yy = 123456789
print('yy = %13.2f' % yy)
print('yy = %2.3e' % yy)
print(yy)

yy =  123456789.00
yy = 1.235e+08
123456789


________________________________________________________________________________________________________________________________

### Reviewing some useful `numpy` functions 

1) When asked to cut off decimal points, formatting rounds the number. We can perform rounding ourselves by using `np.round`

In [26]:
np.round(240000.45675, 5) # round to 3 decimal points

240000.45675

2) The absolute value: `np.abs(x)` or `np.absolute(x)`

In [25]:
a = -2
b = np.abs(a)
print(b)

2


_______________________________________________________________________________________________________________________________

### Problem 1
Write code to calculate the value of the function 
\begin{equation}
f(x, y) = x^y\exp{y} 
\end{equation}
for $x=2.4$ and $y=3$.

Print the output of the calculation. 
Then compare whether the absolute value of the output is greater than 500, and print the difference.

x= 2.4 
y= 3
fxy=np.power(x,y)*np.exp(y)
print('f(2.4,3)=',fxy)
See syntax!!!

__________________________________________________________________________________________________________________________

### Problem 2

Using `numpy` calculate the value of the function below for $x=\pi/4$ and $x=60$ degrees, and print the result.
\begin{equation}
f(x) = x^3\sin{x}
\end{equation}
*Hint:* To convert from $\theta$ degrees to $\omega$ radians, use $\omega = \theta \pi/180$, or use the `numpy` function `radians`.

See the recording for how to do this one

__________________________________________________________________________________________________________________________

### Problem 3
Say, you want to compare two numbers, $a=1.4\times 10^{-8}$ and $b=1.37\times 10^{-7}$, and output a boolean value depending on whether are within a certain tolerance ($\epsilon=1\times 10^{-7}$) of each other or not. Write code to perform the above.

In [53]:
a=1.4e-08
b=1.37e-07
z=np.abs(a-b)
print(1e-07>z)

False


__________________________________________________________________________________________________________________________

### Arrays: dealing with many numbers simultaneously¶

To deal with many numbers at the same time we introduce ARRAYS.
An array is a list of numbers, either created or given to us. We can treat an array as a single object when performing different operations on it.

In [54]:
a=np.array([1.0,2.0,3.0,4.0])
print(a)
b=np.array([0.5,0.5,0.5,0.5])
print(b)

[1. 2. 3. 4.]
[0.5 0.5 0.5 0.5]


In [55]:
c=a+b
print(c)

[1.5 2.5 3.5 4.5]


In [56]:
d=2*a
print(d)

[2. 4. 6. 8.]


#### Array creation functions

Two `numpy` functions are commonly used to generate arrays of numbers with desired properties, namely:

- `np.linspace(beginning, end, number_of_elements)` (we care about the total number of elements in the array)

- `np.arange(beginning, end, step)`: produces an array within a given range and with a given step (we don't care about the number of elements in the array, whatever it takes to cover the range with the given step) 

In [61]:
x1=np.linspace(0,10,6)
print(x1)

[ 0.  2.  4.  6.  8. 10.]


In [63]:
xmin=0
xmax=5+0.00001
xstep=0.1

x2=np.arange(xmin,xmax,xstep)
print(x2)
x2

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5. ]


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ])

**Exercise**

(a) Use the numpy function `linspace` to generate an array of 11 numbers (equally spaced) from -5 to 5. Print your array. How many numbers does your array contain? 

(b) Use the numpy function `arange` to generate an array of numbers from -5 to 5, with spacing equal to 0.5. Print your array. How many numbers does your array contain? Is the end number (number 5 in this exercise) contained in your arrays? If not, what can you do to include it?

In [70]:
x1=np.linspace(-5,5,11)
print(x1)

xmin= -5
xmax= 5.000001
xstep= 0.5

x2=np.arange(xmin,xmax,xstep)
print(x2)

[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5. ]


**Generate arrays filled with constant values**

In many examples and problems, you'll need to initialize arrays with constant values. For example, you'll need to assign the value of 0 to all elements of an array (or the value of 1, or any other constant value); of course, these zero values will change to more meaningful values when the proper calculations will be performed.

An easy way to do this initialization task is by means of the `numpy` function `np.zeros()` (you must not forget to: `import numpy as np`). For example, if you want to initialize with 0s an array named `my_array` which has N=10 elements, you can do it as `my_array = np.zeros(N)`. You will try it in the following examples and exercises.

In [72]:
# example:

N = 20

my_array = np.zeros(N)

print(my_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


You can initialize an array with values of 1 for its elements by means of the np.ones() function.

In [73]:
# example:

my_array = np.ones(N)

print(my_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


***Exercise***: intialize all elements of array `my_array` with the value of 3.

In [77]:
my_array=3*np.ones(N)
print(my_array)


[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
